version: '3.8'

services:
  yolo-trainer:
    build: .
    image: phase-2-image:latest
    container_name: vision_phase2_trainer
    ipc: host
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
    volumes:
      - ./:/app
      - ./runs:/app/runs
      - ./data:/app/data/kitti
      - ~/Desktop:/app/desktop 
      
    command: python src/training/train.py